#!/bin/sh
set -e

action="$1"

if [ "$action" != configure ]; then
    exit 0
fi

# Add group for crontabs
getent group crontab > /dev/null 2>&1 || addgroup --system crontab

# Fixup crontab binary for new group 'crontab'.
if ! dpkg-statoverride --list /usr/bin/byte-rpc-crontab > /dev/null ; then
    dpkg-statoverride --update --add root crontab 2755 /usr/bin/byte-rpc-crontab
fi


#DEBHELPER#
